name: qazaq_tili
description: Qazaqsha — интерактивное изучение казахского языка.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  speech_to_text: ^7.5.0

flutter:
  uses-material-design: true
